"""Tests for marimo notebook validation using marimo's own get_notebook_status.

These tests verify that notebooks generated by our converter are considered
valid by marimo's internal validation, catching structural issues that
ast.parse alone would miss (e.g. missing __generated_with, malformed cells).
"""

import ast
import tempfile
from pathlib import Path

import pytest

from marimo._ast.load import LoadResult, get_notebook_status
from marimo_dagster._ir import CellNode, NotebookIR, ScriptMetadata
from marimo_dagster._marimo_ast import generate_marimo
from marimo_dagster.converter import dagster_to_marimo

EXAMPLES_DIR = Path(__file__).parent / "examples"


def _validate_marimo_source(source: str) -> LoadResult:
    """Write source to a temp file and validate it with marimo."""
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False
    ) as f:
        f.write(source)
        f.flush()
        result = get_notebook_status(f.name)
        Path(f.name).unlink()
        return result


class TestGeneratedNotebookValidation:
    """Verify generated marimo notebooks pass marimo's own validation."""

    def test_minimal_notebook_is_valid(self) -> None:
        """A minimal generated notebook should be valid according to marimo."""
        ir = NotebookIR(cells=[])
        result = generate_marimo(ir)
        status = _validate_marimo_source(result)
        assert status.status == "valid", (
            f"Expected 'valid' but got '{status.status}'. "
            f"Violations: {status.notebook.violations if status.notebook else 'N/A'}"
        )

    def test_single_cell_notebook_is_valid(self) -> None:
        """A notebook with one code cell should be valid."""
        ir = NotebookIR(
            cells=[
                CellNode(
                    name="my_data",
                    body_stmts=ast.parse('my_data = {"x": 1}').body,
                    inputs=[],
                    outputs=["my_data"],
                )
            ],
        )
        result = generate_marimo(ir)
        status = _validate_marimo_source(result)
        assert status.status == "valid", (
            f"Expected 'valid' but got '{status.status}'. "
            f"Violations: {status.notebook.violations if status.notebook else 'N/A'}"
        )

    def test_multi_cell_with_deps_is_valid(self) -> None:
        """A notebook with multiple cells and dependencies should be valid."""
        ir = NotebookIR(
            cells=[
                CellNode(
                    name="raw_data",
                    body_stmts=ast.parse("raw_data = [1, 2, 3]").body,
                    inputs=[],
                    outputs=["raw_data"],
                ),
                CellNode(
                    name="total",
                    body_stmts=ast.parse("total = sum(raw_data)").body,
                    inputs=["raw_data"],
                    outputs=["total"],
                ),
            ],
        )
        result = generate_marimo(ir)
        status = _validate_marimo_source(result)
        assert status.status == "valid", (
            f"Expected 'valid' but got '{status.status}'. "
            f"Violations: {status.notebook.violations if status.notebook else 'N/A'}"
        )

    def test_notebook_with_metadata_is_valid(self) -> None:
        """A notebook with PEP 723 metadata should be valid."""
        ir = NotebookIR(
            cells=[
                CellNode(
                    name="x",
                    body_stmts=ast.parse("x = 1").body,
                    inputs=[],
                    outputs=["x"],
                )
            ],
            metadata=ScriptMetadata(
                requires_python=">=3.12",
                dependencies=["marimo", "polars>=1.0"],
            ),
        )
        result = generate_marimo(ir)
        status = _validate_marimo_source(result)
        assert status.status == "valid", (
            f"Expected 'valid' but got '{status.status}'. "
            f"Violations: {status.notebook.violations if status.notebook else 'N/A'}"
        )

    def test_notebook_with_docstring_is_valid(self) -> None:
        """A notebook with a module docstring should be valid."""
        ir = NotebookIR(
            cells=[
                CellNode(
                    name="x",
                    body_stmts=ast.parse("x = 1").body,
                    inputs=[],
                    outputs=["x"],
                )
            ],
            module_docstring="Test notebook with a docstring.",
        )
        result = generate_marimo(ir)
        status = _validate_marimo_source(result)
        assert status.status == "valid", (
            f"Expected 'valid' but got '{status.status}'. "
            f"Violations: {status.notebook.violations if status.notebook else 'N/A'}"
        )


class TestDagsterToMarimoValidation:
    """Verify dagster-to-marimo conversion produces valid marimo notebooks."""

    def test_simple_asset_conversion_is_valid(self) -> None:
        """Converting a simple dagster asset should produce a valid notebook."""
        source = (
            "import dagster as dg\n"
            "\n"
            "@dg.asset\n"
            "def my_data() -> dict:\n"
            '    return {"x": 1}\n'
        )
        result = dagster_to_marimo(source)
        status = _validate_marimo_source(result)
        assert status.status == "valid", (
            f"Expected 'valid' but got '{status.status}'. "
            f"Violations: {status.notebook.violations if status.notebook else 'N/A'}"
        )

    def test_two_assets_with_dep_is_valid(self) -> None:
        """Converting two assets with dependency should produce a valid notebook."""
        source = (
            "import dagster as dg\n"
            "\n"
            "@dg.asset\n"
            "def raw_data() -> list:\n"
            "    return [1, 2, 3]\n"
            "\n"
            "@dg.asset\n"
            "def processed(raw_data: list) -> float:\n"
            "    return sum(raw_data) / len(raw_data)\n"
        )
        result = dagster_to_marimo(source)
        status = _validate_marimo_source(result)
        assert status.status == "valid", (
            f"Expected 'valid' but got '{status.status}'. "
            f"Violations: {status.notebook.violations if status.notebook else 'N/A'}"
        )

    def test_asset_with_pep723_metadata_is_valid(self) -> None:
        """Assets with PEP 723 metadata should produce a valid notebook."""
        source = (
            "# /// script\n"
            '# requires-python = ">=3.12"\n'
            "# dependencies = [\n"
            '#     "dagster>=1.9.0",\n'
            '#     "polars>=1.0",\n'
            "# ]\n"
            "# ///\n"
            "import dagster as dg\n"
            "\n"
            "@dg.asset\n"
            "def my_data() -> dict:\n"
            '    return {"x": 1}\n'
        )
        result = dagster_to_marimo(source)
        status = _validate_marimo_source(result)
        assert status.status == "valid", (
            f"Expected 'valid' but got '{status.status}'. "
            f"Violations: {status.notebook.violations if status.notebook else 'N/A'}"
        )


class TestDagsterExampleValidation:
    """Verify all dagster example files convert to valid marimo notebooks."""

    @pytest.fixture(
        params=sorted(
            p
            for tier in (EXAMPLES_DIR / "dagster").iterdir()
            if tier.is_dir()
            for p in tier.glob("*.py")
            if p.name != "__init__.py"
        ),
        ids=lambda p: f"{p.parent.name}/{p.stem}",
    )
    def dagster_example(self, request: pytest.FixtureRequest) -> Path:
        return request.param

    def test_dagster_example_converts_to_valid_marimo(
        self, dagster_example: Path
    ) -> None:
        """Each dagster example should convert to a valid marimo notebook."""
        source = dagster_example.read_text()
        result = dagster_to_marimo(source)
        status = _validate_marimo_source(result)
        assert status.status == "valid", (
            f"Converted {dagster_example.name} is not valid marimo. "
            f"Status: {status.status}. "
            f"Violations: {status.notebook.violations if status.notebook else 'N/A'}"
        )


class TestMarimoRoundTripValidation:
    """Verify marimo examples remain valid after round-trip conversion."""

    @pytest.fixture(
        params=sorted(
            p
            for tier in (EXAMPLES_DIR / "marimo").iterdir()
            if tier.is_dir()
            for p in tier.glob("*.py")
            if p.name != "__init__.py"
        ),
        ids=lambda p: f"{p.parent.name}/{p.stem}",
    )
    def marimo_example(self, request: pytest.FixtureRequest) -> Path:
        return request.param

    def test_marimo_roundtrip_produces_valid_notebook(
        self, marimo_example: Path
    ) -> None:
        """marimo -> dagster -> marimo should still be valid marimo."""
        from marimo_dagster.converter import marimo_to_dagster

        source = marimo_example.read_text()
        dagster_source = marimo_to_dagster(source)
        marimo_source = dagster_to_marimo(dagster_source)
        status = _validate_marimo_source(marimo_source)
        assert status.status == "valid", (
            f"Round-trip of {marimo_example.name} is not valid marimo. "
            f"Status: {status.status}. "
            f"Violations: {status.notebook.violations if status.notebook else 'N/A'}"
        )
